[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-unknown-linux-musl]
linker = "rust-lld"
rustflags = ['-C', 'target-feature=+crt-static']


# [build]
# rustflags = ["--cfg", "tokio_unstable"]
# rustdocflags = ["--cfg", "tokio_unstable"]
