name: Rust

on: workflow_dispatch
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: build app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install librust-atk-dev build-essential libgtk-3-dev
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install librust-atk-dev build-essential libgtk-3-dev

      - name: Build
        run: cargo build --profile opt --verbose
      
      - name: Upload binary
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: egui_code-${{ matrix.os }}
          path: target/opt/egui_code
          
      - name: Upload binary
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: egui_code-${{ matrix.os }}.exe
          path: target\opt\egui_code.exe


